name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Cache Clear
      run: php artisan cache:clear
    - name: Route Clear
      run: php artisan route:clear
    - name: Config Clear 
      run: php artisan config:clear
    - name: View Clear
      run: php artisan view:clear
    - name: Storage Link
      run: php artisan storage:link
    - name: Directory Permissions 2
      run: chmod -R 755 
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: php artisan migrate:fresh
    - name: Setup seed database
      run: php artisan db:seed
